version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - api
  db:
    build:
      context: ./db
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_EXPOSE_PORT}:${DB_CONTAINER_PORT}"
