version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  db:
    build:
      context: ./db
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    restart: always
