export const ACTION_REQUEST_POST = 'ACTION_REQUEST_POST';
export const ACTION_ERROR_POST = 'ACTION_ERROR_POST';
export const GET_ALL_POST = 'GET_ALL_POST';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';

export const ACTION_REQUEST_CONNECTION = 'ACTION_REQUEST_CONNECTION';
export const ACTION_ERROR_CONNECTION = 'ACTION_ERROR_CONNECTION';
export const GET_ALL_CONNECTION = 'GET_ALL_CONNECTION';
export const GET_CONNECTION = 'GET_CONNECTION';
export const ADD_CONNECTION = 'ADD_CONNECTION';
export const DELETE_CONNECTION = 'DELETE_CONNECTION';

export const ACTION_REQUEST_USER = 'ACTION_REQUEST_USER';
export const ACTION_ERROR_USER = 'ACTION_ERROR_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOAD_USER = 'LOAD_USER';
export const LOGOUT = 'LOGOUT';

export const INIT = 'INIT';
export const INIT_DONE = 'INIT_DONE';
